{
 "title": "Sprint 3",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Model", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Predictions value",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(price_histogram_sum[5m]) / rate(price_histogram_count[5m])",
     "legendFormat": "average"
    },
    {
     "expr": "histogram_quantile(\n  0.5,\n  sum by (le) (rate(price_histogram_bucket[5m]))\n)",
     "legendFormat": "median"
    }
   ]
  },
  {
   "title": "Number of predictions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(positive_counter_total[1m])",
     "legendFormat": "Predictions"
    }
   ]
  },
  {
   "title": "Process memory",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Applied metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true
  },
  {
   "title": "Requests by type",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (status) (rate(http_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average response size",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(http_response_size_bytes_sum{handler=\"/api/predict\"}[5m])\n/\nrate(http_response_size_bytes_count{handler=\"/api/predict\"}[5m])",
     "legendFormat": "response size"
    }
   ]
  }
 ]
}